server:
  port: 8001
eureka:
    client:
      serviceUrl:
        defaultZone: http://BLOG-EUREKA-01:8761/eureka,http://BLOG-EUREKA-02:8761/eureka
spring:
  application:
    name: BLOG-CONFIG-SERVER
  cloud:
    config:
      server:
        default-application-name: BLOG-CONFIG-SERVER
        git:
          uri: https://gitee.com/fpfos/fpfos-blog-config
          username: fpfos@hotmail.com
          password: Fupengfei1130
          search-paths: /**
      label: master