server:
  port: 8761
spring:
    application:
      name: BLOG-EUREKA # eureka.instance.appname 默认取值
eureka:
  instance:
    hostname: BLOG-EUREKA-01 # 实例名
  client:
    registry-fetch-interval-seconds: 60 # seconds
    serviceUrl:
      defaultZone: http://BLOG-EUREKA-01:8761/eureka,http://BLOG-EUREKA-02:8761/eureka
  server:
    enable-self-preservation: false

